// import type { Metadata } from "next";
import Header from '@/components/Header';\nimport Footer from '@/components/Footer';\nimport { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children,
}) {
  return (
    <html lang="ar">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} dir="rtl"
      >
        <Header />\n        <main className="flex-grow">{children}</main>\n        <Footer />
      </body>
    </html>
  );
}
